<?php

namespace PetroPack\ProductoBundle\Repository;

/**
 * DescuentoProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescuentoProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
