<?php

namespace PetroPack\ProductoBundle\Repository;

/**
 * ImagenProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
