<?php

namespace PetroPack\VentaBundle\Repository;

/**
 * ItemVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
