<?php

namespace Proxies\__CG__\PetroPack\ProductoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \PetroPack\ProductoBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'presentacion', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'precio_unidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'tipo', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'cantidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'cod_producto'];
        }

        return ['__isInitialized__', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'presentacion', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'precio_unidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'tipo', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'cantidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\Producto' . "\0" . 'cod_producto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentacion($presentacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentacion', [$presentacion]);

        return parent::setPresentacion($presentacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentacion', []);

        return parent::getPresentacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecioUnidad($precioUnidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecioUnidad', [$precioUnidad]);

        return parent::setPrecioUnidad($precioUnidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecioUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecioUnidad', []);

        return parent::getPrecioUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodProducto($codProducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodProducto', [$codProducto]);

        return parent::setCodProducto($codProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodProducto', []);

        return parent::getCodProducto();
    }

}
