<?php

namespace Proxies\__CG__\PetroPack\ProductoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DescuentoProducto extends \PetroPack\ProductoBundle\Entity\DescuentoProducto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'producto_id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'cantidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'descuento', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'fecha_incial', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'fecha_final', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'created_at', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'updated_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'producto_id', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'cantidad', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'descuento', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'fecha_incial', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'fecha_final', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'created_at', '' . "\0" . 'PetroPack\\ProductoBundle\\Entity\\DescuentoProducto' . "\0" . 'updated_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DescuentoProducto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoId($productoId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoId', [$productoId]);

        return parent::setProductoId($productoId);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoId', []);

        return parent::getProductoId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuento($descuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuento', [$descuento]);

        return parent::setDescuento($descuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuento', []);

        return parent::getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaIncial($fechaIncial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaIncial', [$fechaIncial]);

        return parent::setFechaIncial($fechaIncial);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaIncial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaIncial', []);

        return parent::getFechaIncial();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinal($fechaFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinal', [$fechaFinal]);

        return parent::setFechaFinal($fechaFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinal', []);

        return parent::getFechaFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
